// Writes the Pli wordmarks and symbol from their construction.
//   node brand/scripts/logo/build.mjs
//
//   brand/wordmark/pli-wordmark-ink.svg          primary wordmark, for light backgrounds
//   brand/wordmark/pli-wordmark-ice.svg          primary wordmark, for dark backgrounds
//   brand/wordmark/pli-wordmark-crease-ink.svg   secondary motion wordmark, light backgrounds
//   brand/wordmark/pli-wordmark-crease-ice.svg   secondary motion wordmark, dark backgrounds
//   brand/symbol/pli-symbol.svg                  the icon's pane on its hinge, for favicons
//
// Every file is plain vector art: outlined paths (no <text>, no font), linear
// gradients, masks and clip paths, and no filter, so nothing depends on a
// rasterizing effect (checked in Chrome and librsvg). Colors come from
// brand/tokens/tokens.json.
import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { glyphs, M } from './letters.mjs';
import { f, roundedPoly } from '../lib/geom.mjs';
import { C, IRI, rgb } from '../lib/tokens.mjs';
import { G as ICON } from '../icon/layers.mjs';

const BRAND = fileURLToPath(new URL('../../', import.meta.url));

const TONES = {
  ink: { name: 'Ink', fill: C.ink, use: 'light backgrounds (White, Paper)' },
  ice: { name: 'Ice', fill: C.ice, use: 'dark backgrounds (Night, Slate)' },
};

// ---------- SVG helpers

const round3 = (n) => Math.round(n * 1000) / 1000;
const stop = (o, color, a = 1) =>
  `<stop offset="${f(o)}" stop-color="${color}"${a === 1 ? '' : ` stop-opacity="${round3(a)}"`}/>`;
const iriStops = () => IRI.map((s) => stop(s.position, s.color)).join('');
const linear = (id, [x1, y1, x2, y2], stops) =>
  `<linearGradient id="${id}" x1="${f(x1)}" y1="${f(y1)}" x2="${f(x2)}" y2="${f(y2)}" gradientUnits="userSpaceOnUse">${stops}</linearGradient>`;
const maskRect = (id, [x, y, w, h], fill) =>
  `<mask id="${id}" maskUnits="userSpaceOnUse" x="${f(x)}" y="${f(y)}" width="${f(w)}" height="${f(h)}">` +
  `<rect x="${f(x)}" y="${f(y)}" width="${f(w)}" height="${f(h)}" fill="${fill}"/></mask>`;
const doc = ({ id, w, h, comment, defs, body }) =>
  `<svg xmlns="http://www.w3.org/2000/svg" width="${f(w)}" height="${f(h)}" viewBox="0 0 ${f(w)} ${f(h)}" role="img" aria-labelledby="${id}-title">\n` +
  `<!-- ${comment} -->\n` +
  `<title id="${id}-title">Pli</title>\n` +
  `<defs>\n${defs.join('\n')}\n</defs>\n` +
  `${body.join('\n')}\n</svg>\n`;

const files = {};

// ---------- Primary wordmark (A1 "Pane")
// Crisp letters; the dot of the i is a small pane of glass whose top edge
// catches the light: a thin iridescent band at the very top that fades into
// the pane, as the rim does on the icon.

const RIM = { solid: 3, fade: 5.2 }; // units from the top edge: full-strength band, then the end of the fade

function wordmark(tone) {
  const t = TONES[tone];
  const id = `pli-wordmark-${tone}`;
  const g = glyphs();
  const { x0, x1, y0, y1 } = g.bounds;
  const dx = -x0, dy = -y0;
  const w = x1 - x0, h = y1 - y0;
  const dotX = g.ix + M.S / 2 - M.dotW / 2 + dx;
  const dotTop = M.dotTop + dy, dotH = M.dotBottom - M.dotTop;
  const letters = [g.p, g.counter, g.l, g.i, g.dot].map((c) => c.d(dx, dy)).join('');
  files[`wordmark/${id}.svg`] = doc({
    id, w, h,
    comment: `Pli wordmark, ${t.name}, for ${t.use}. Generated by brand/scripts/logo/build.mjs; usage in docs/brand/BRAND.md.`,
    defs: [
      linear(`${id}-rim`, [dotX, 0, dotX + M.dotW, 0], iriStops()),
      linear(`${id}-rim-fade`, [0, dotTop, 0, dotTop + RIM.fade],
        stop(0, '#FFFFFF') + stop(RIM.solid / RIM.fade, '#FFFFFF') +
        stop((RIM.solid + 0.3 * (RIM.fade - RIM.solid)) / RIM.fade, '#FFFFFF', 0.4) + stop(1, '#FFFFFF', 0)),
      maskRect(`${id}-rim-mask`, [dotX, dotTop, M.dotW, dotH], `url(#${id}-rim-fade)`),
    ],
    body: [
      `<path fill="${t.fill}" d="${letters}"/>`,
      `<path fill="url(#${id}-rim)" mask="url(#${id}-rim-mask)" d="${g.dot.d(dx, dy)}"/>`,
    ],
  });
}

// ---------- Secondary motion wordmark (the crease)
// The same letters crossed by the fold line at half the x-height: sharp
// below, frosted above, the line catching the iridescent light. The frost is
// baked as vector art instead of a blur filter: the upper letters are filled
// with a vertical gradient whose opacity falls toward the top (frost rising),
// and their edges are softened by a halo of widening strokes (a smooth outer
// falloff), clipped to the outside of the letters.
//
// No group carries a mask or an opacity, and no two translucent shapes
// overlap: every fade is in the paint of the shape it fades. AppKit's SVG
// renderer (CoreSVG) applies a group's mask to each element of the group
// separately, which drew the inner halves of the halo strokes through the
// frosted letters as dark outlines; built this way, the file renders the same
// in AppKit (NSImage), Chrome and librsvg.

const FROST = { atCrease: 0.56, atTop: 0.3, halo: 0.6, haloReach: 4, haloSteps: 12 };
const CREASE = { overhang: 14, line: 2.4, bloom: 6, bloomAlpha: { ink: 0.5, ice: 0.4 }, shade: 0.16 };

// Stroke widths and opacities whose stack (widest first) gives the outer
// falloff A * (1 - smoothstep(0, R, distance)).
function haloRings(A, R, N) {
  const smooth = (x) => { const u = Math.min(1, Math.max(0, x)); return u * u * (3 - 2 * u); };
  const step = R / N;
  const rings = [];
  let outer = 0;
  for (let j = N; j >= 1; j--) {
    const target = A * (1 - smooth(((j - 0.5) * step) / R));
    rings.push([2 * j * step, Math.max(0, 1 - (1 - target) / (1 - outer))]);
    outer = target;
  }
  return rings;
}

// The iridescent gradient's color at position u (0 to 1), as the gradient
// interpolates it (linearly in sRGB between its stops).
function iriAt(u) {
  const i = Math.max(1, IRI.findIndex((s) => s.position >= u));
  const a = IRI[i - 1], b = IRI[i];
  const k = (u - a.position) / (b.position - a.position);
  const [ra, ga, ba] = rgb(a.color), [rb, gb, bb] = rgb(b.color);
  return '#' + [ra + (rb - ra) * k, ga + (gb - ga) * k, ba + (bb - ba) * k]
    .map((v) => Math.round(v).toString(16).padStart(2, '0').toUpperCase()).join('');
}

function creaseWordmark(tone) {
  const t = TONES[tone];
  const id = `pli-wordmark-crease-${tone}`;
  const g = glyphs(M, { upperReach: 8 });
  const { x0, x1, y0, y1 } = g.bounds;
  const pad = FROST.haloReach; // room for the halo above the l and around the dot
  const dx = CREASE.overhang - x0, dy = pad - y0;
  const w = x1 - x0 + 2 * CREASE.overhang, h = y1 - y0 + pad;
  const yc = g.creaseY + dy;
  const lower = g.lower.map((c) => c.d(dx, dy)).join('');
  const upper = g.upper.map((c) => c.d(dx, dy)).join('');
  // Frost: the letters' opacity at the crease and at the top; each halo ring
  // is solved at both heights, so the stack gives the same falloff as the
  // letters' own frost, anywhere between.
  const frost = (gid, a0, a1) => linear(gid, [0, yc, 0, pad], stop(0, t.fill, a0) + stop(1, t.fill, a1));
  const atC = haloRings(FROST.halo * FROST.atCrease, FROST.haloReach, FROST.haloSteps);
  const atT = haloRings(FROST.halo * FROST.atTop, FROST.haloReach, FROST.haloSteps);
  const rings = atC.map(([sw, a], j) => ({ sw, grad: frost(`${id}-halo-${j + 1}`, a, atT[j][1]) }));
  // The ends of the crease fade out over the overhang, in the paints.
  const e = CREASE.overhang / w;
  const iriEnds = [[0, 0], [e, 1], ...IRI.filter((s) => s.position > e && s.position < 1 - e).map((s) => [s.position, 1]), [1 - e, 1], [1, 0]]
    .map(([u, a]) => stop(u, iriAt(u), a)).join('');
  const shade = tone === 'ink'
    ? [`<path d="M0 ${f(yc + 1.7)}H${f(w)}" fill="none" stroke="url(#${id}-shade)" stroke-width="0.9"/>`]
    : [];
  files[`wordmark/${id}.svg`] = doc({
    id, w, h,
    comment: `Pli motion wordmark (secondary), ${t.name}, for ${t.use}: animated moments only. ` +
      `Letters placed as in pli-wordmark-${tone}.svg, offset by (${f(dx)}, ${f(pad)}). Generated by brand/scripts/logo/build.mjs.`,
    defs: [
      `<path id="${id}-upper" d="${upper}"/>`,
      `<clipPath id="${id}-above"><rect x="0" y="0" width="${f(w)}" height="${f(yc)}"/></clipPath>`,
      // Everything but the upper letters. The frame runs counterclockwise and
      // every letter clockwise, so the nonzero and evenodd rules agree (AppKit
      // clips with nonzero whatever the clip-rule says).
      `<clipPath id="${id}-outside"><path clip-rule="evenodd" d="M0 0V${f(h)}H${f(w)}V0Z${upper}"/></clipPath>`,
      frost(`${id}-frost`, FROST.atCrease, FROST.atTop),
      ...rings.map((r) => r.grad),
      linear(`${id}-iri`, [0, 0, w, 0], iriEnds),
      linear(`${id}-bloom-fade`, [0, yc - CREASE.bloom, 0, yc + CREASE.bloom],
        stop(0, '#FFFFFF', 0) + stop(0.5, '#FFFFFF', CREASE.bloomAlpha[tone]) + stop(1, '#FFFFFF', 0)),
      maskRect(`${id}-bloom`, [0, yc - CREASE.bloom, w, 2 * CREASE.bloom], `url(#${id}-bloom-fade)`),
      ...(tone === 'ink' ? [linear(`${id}-shade`, [0, 0, w, 0],
        stop(0, C.ink, 0) + stop(e, C.ink, CREASE.shade) + stop(1 - e, C.ink, CREASE.shade) + stop(1, C.ink, 0))] : []),
    ],
    body: [
      `<path fill="${t.fill}" d="${lower}"/>`,
      `<g clip-path="url(#${id}-above)">`,
      `<g clip-path="url(#${id}-outside)">`,
      ...rings.map((r, j) => `<use href="#${id}-upper" fill="none" stroke="url(#${id}-halo-${j + 1})" stroke-width="${f(r.sw)}" stroke-linejoin="round"/>`),
      `</g>`,
      `<use href="#${id}-upper" fill="url(#${id}-frost)"/>`,
      `</g>`,
      `<rect x="0" y="${f(yc - CREASE.bloom)}" width="${f(w)}" height="${f(2 * CREASE.bloom)}" fill="url(#${id}-iri)" mask="url(#${id}-bloom)"/>`,
      ...shade,
      `<path d="M0 ${f(yc)}H${f(w)}" fill="none" stroke="url(#${id}-iri)" stroke-width="${CREASE.line}"/>`,
    ],
  });
}

// ---------- Symbol: the icon's pane on its hinge, on transparency
// The icon's geometry (ICON, from brand/scripts/icon/layers.mjs) mapped by a
// similarity onto a 16 x 16 pixel grid (64 units per pixel at 16 px): the
// pane's top edge on y = 192 (a pixel line at 16, 32 and 64 px), the hinge
// centered on y = 800 (one whole pixel row at 16 px, two at 32 px), the whole
// centered on x = 512. The pane carries its own dark glass, so the symbol
// reads on light and dark browser chrome alike; the hinge is Mist, which
// holds on both.

function symbol() {
  const id = 'pli-symbol';
  const yTop = 192, yBot = 800;
  const s = (yBot - yTop) / (ICON.hingeY - ICON.yTop);
  const X = (x) => 512 + (x - 512) * s;
  const Y = (y) => yTop + (y - ICON.yTop) * s;
  const paneD = roundedPoly(
    [[X(ICON.topL), Y(ICON.yTop)], [X(ICON.topR), Y(ICON.yTop)], [X(ICON.botR), Y(ICON.yBot)], [X(ICON.botL), Y(ICON.yBot)]],
    [ICON.rTop * s, ICON.rTop * s, ICON.rBot * s, ICON.rBot * s]);
  const topL = X(ICON.topL), topR = X(ICON.topR);
  // The hinge: the icon's span, but one pixel row thick at 16 px (64 units),
  // where the icon's thin core and halo would blur into the pane.
  const hinge = { x0: X(ICON.hingeL), x1: X(ICON.hingeR), y: Y(ICON.hingeY), t: 64 };
  const rimH = 96, edge = 20;
  files[`symbol/${id}.svg`] = doc({
    id, w: 1024, h: 1024,
    comment: 'Pli symbol: the app icon\'s pane on its hinge, on transparency. For favicons and small sizes (16 to 64 px); ' +
      'larger, use the app icon. Generated by brand/scripts/logo/build.mjs.',
    defs: [
      linear(`${id}-glass`, [0, yTop, 0, yBot], stop(0, C.slate) + stop(1, C.night)),
      linear(`${id}-frost`, [0, yTop, 0, yBot],
        stop(0, C.ice, 0.92) + stop(0.4, C.ice, 0.5) + stop(0.75, C.glacier, 0.2) + stop(1, C.glacier, 0.14)),
      linear(`${id}-iri`, [topL, 0, topR, 0], iriStops()),
      linear(`${id}-rim-fade`, [0, yTop, 0, yTop + rimH], stop(0, '#FFFFFF') + stop(0.4, '#FFFFFF', 0.85) + stop(1, '#FFFFFF', 0)),
      maskRect(`${id}-rim`, [0, yTop, 1024, rimH], `url(#${id}-rim-fade)`),
      linear(`${id}-edge`, [0, yTop, 0, yBot], stop(0, '#FFFFFF', 0.9) + stop(1, '#FFFFFF', 0.4)),
      `<clipPath id="${id}-pane"><path d="${paneD}"/></clipPath>`,
      linear(`${id}-hinge-fade`, [hinge.x0, 0, hinge.x1, 0],
        stop(0, '#FFFFFF', 0) + stop(0.07, '#FFFFFF') + stop(0.93, '#FFFFFF') + stop(1, '#FFFFFF', 0)),
      maskRect(`${id}-hinge`, [hinge.x0, hinge.y - hinge.t / 2, hinge.x1 - hinge.x0, hinge.t], `url(#${id}-hinge-fade)`),
    ],
    body: [
      `<path fill="url(#${id}-glass)" d="${paneD}"/>`,
      `<path fill="url(#${id}-frost)" d="${paneD}"/>`,
      `<path fill="url(#${id}-iri)" mask="url(#${id}-rim)" d="${paneD}"/>`,
      `<path fill="none" stroke="url(#${id}-edge)" stroke-width="${2 * edge}" clip-path="url(#${id}-pane)" d="${paneD}"/>`,
      `<rect x="${f(hinge.x0)}" y="${f(hinge.y - hinge.t / 2)}" width="${f(hinge.x1 - hinge.x0)}" height="${hinge.t}" rx="${hinge.t / 2}" fill="${C.mist}" mask="url(#${id}-hinge)"/>`,
    ],
  });
}

wordmark('ink');
wordmark('ice');
creaseWordmark('ink');
creaseWordmark('ice');
symbol();

for (const [path, content] of Object.entries(files)) {
  mkdirSync(`${BRAND}${path.split('/')[0]}`, { recursive: true });
  writeFileSync(`${BRAND}${path}`, content);
}
console.log(`wrote ${Object.keys(files).map((p) => `brand/${p}`).join(', ')}`);
